# Generated by Django 2.1.1 on 2018-09-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Cover'),
        ),
    ]
